using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Tessera.Persistence;
using Tessera.Queue;
using Tessera.Storage;

namespace Tessera.Worker.Tests;

public sealed class TranscodeServiceTests(WorkerFixture fixture) : IClassFixture<WorkerFixture>
{
    [Fact]
    public async Task Transcodes_an_uploaded_video_to_hls_and_marks_it_ready()
    {
        var clip = await GenerateClipAsync();
        var videoId = await SeedVideoAsync(clip);

        using (var scope = fixture.Services.CreateScope())
        {
            await scope.ServiceProvider.GetRequiredService<TranscodeService>()
                .ProcessAsync(videoId, CancellationToken.None);
        }

        await AssertStatusAsync(videoId, VideoStatus.Ready);

        // The measured duration lands with Ready: the clip is two seconds long.
        using (var scope = fixture.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<TesseraDbContext>();
            var video = await db.Videos.AsNoTracking().SingleAsync(v => v.Id == videoId);
            Assert.NotNull(video.DurationSeconds);
            Assert.InRange(video.DurationSeconds!.Value, 1.5, 2.5);
        }

        var storage = fixture.Services.GetRequiredService<IObjectStorage>();
        Assert.NotNull(await storage.GetSizeAsync($"videos/{videoId}/hls/master.m3u8", CancellationToken.None));
        Assert.NotNull(await storage.GetSizeAsync($"videos/{videoId}/hls/v0_index.m3u8", CancellationToken.None));
        Assert.NotNull(await storage.GetSizeAsync($"videos/{videoId}/hls/v1_index.m3u8", CancellationToken.None));
    }

    [Fact]
    public async Task Marks_a_video_failed_when_the_input_is_not_decodable()
    {
        var junkPath = Path.Combine(Path.GetTempPath(), $"junk-{Guid.NewGuid():N}.bin");
        await File.WriteAllBytesAsync(junkPath, new byte[512]);
        var videoId = await SeedVideoAsync(junkPath);

        using (var scope = fixture.Services.CreateScope())
        {
            await scope.ServiceProvider.GetRequiredService<TranscodeService>()
                .ProcessAsync(videoId, CancellationToken.None);
        }

        await AssertStatusAsync(videoId, VideoStatus.Failed);
    }

    [Fact]
    public async Task Queue_round_trips_and_recovers_in_flight_jobs()
    {
        var queue = fixture.Services.GetRequiredService<TranscodeQueue>();
        var id = Guid.NewGuid();

        await queue.EnqueueAsync(id);
        Assert.Equal(id, await queue.ClaimAsync());
        Assert.Null(await queue.ClaimAsync());

        // A crashed worker leaves the job in flight; startup recovery restores it.
        await queue.RequeueInFlightAsync();
        Assert.Equal(id, await queue.ClaimAsync());

        await queue.CompleteAsync(id);
        await queue.RequeueInFlightAsync();
        Assert.Null(await queue.ClaimAsync());
    }

    // A two-second real clip (test pattern plus a tone) generated by ffmpeg itself.
    private static async Task<string> GenerateClipAsync()
    {
        var path = Path.Combine(Path.GetTempPath(), $"clip-{Guid.NewGuid():N}.mp4");
        var startInfo = new ProcessStartInfo
        {
            FileName = WorkerFixture.ToolPath("ffmpeg"),
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var argument in new[]
        {
            "-y", "-f", "lavfi", "-i", "testsrc2=duration=2:size=320x240:rate=15",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
            "-shortest", "-c:v", "libx264", "-preset", "veryfast", "-c:a", "aac", path,
        })
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = Process.Start(startInfo)!;
        // Drain stderr while waiting: an unread redirected pipe fills and deadlocks.
        var standardError = process.StandardError.ReadToEndAsync();
        using var timeout = new CancellationTokenSource(TimeSpan.FromMinutes(2));
        await process.WaitForExitAsync(timeout.Token);
        Assert.True(process.ExitCode == 0, await standardError);
        return path;
    }

    private async Task<Guid> SeedVideoAsync(string filePath)
    {
        var videoId = Guid.NewGuid();
        var ownerId = Guid.NewGuid();
        var key = $"uploads/{ownerId}/{videoId}";

        var storage = fixture.Services.GetRequiredService<IObjectStorage>();
        await storage.UploadFileAsync(key, filePath, "video/mp4", CancellationToken.None);

        using var scope = fixture.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<TesseraDbContext>();
        db.Users.Add(new TesseraUser
        {
            Id = ownerId,
            UserName = $"u-{ownerId:N}",
            Email = $"u-{ownerId:N}@tessera.test",
            CreatedAt = DateTimeOffset.UtcNow,
        });
        db.Videos.Add(new Video
        {
            Id = videoId,
            OwnerId = ownerId,
            Title = "clip",
            OriginalFileName = "clip.mp4",
            ContentType = "video/mp4",
            SizeBytes = new FileInfo(filePath).Length,
            StorageKey = key,
            Status = VideoStatus.Uploaded,
            CreatedAt = DateTimeOffset.UtcNow,
        });
        await db.SaveChangesAsync();
        return videoId;
    }

    private async Task AssertStatusAsync(Guid videoId, VideoStatus expected)
    {
        using var scope = fixture.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<TesseraDbContext>();
        var video = await db.Videos.AsNoTracking().SingleAsync(v => v.Id == videoId);
        Assert.Equal(expected, video.Status);
    }
}
